#@Author: LIUXIANG
#@Time  :  2019/7/29 14:51
#江门版本？：开关启用江门开发商资质版本
import time
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium import webdriver
from aip import AipOcr
from PIL import Image
from selenium.webdriver.support.ui import WebDriverWait
import os
import unittest
class LoginTest(unittest.TestCase):
    '''开发商企业入网申请提交或异常功能点'''
    def test_01(self):
        '''江门开发商企业正常入网申请提交成功'''
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2) # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx') #http://125.91.215.239:8090/
        time.sleep(5)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(5)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(5)
        #填写企业基本信息
        a ="E83112"
        b="明明空旷"
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys( "江门" + b + "有限公司")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys(b)
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("87876766")
        driver.find_element_by_xpath("//*[@id= 'FRXB']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'ZJLX']/option[4]").click()
        driver.find_element_by_id("FRSFZH").send_keys("11"+a )
        driver.find_element_by_id("YYZZH").send_keys("AA9887773")
        driver.find_element_by_id("ZZRQ").send_keys("2019-04-07")
        driver.find_element_by_id("YYZZDQR").send_keys("2024-04-07")
        driver.find_element_by_xpath("//*[@id= 'DJZCLX']/option[2]").click()
        driver.find_element_by_id("ZCZB").send_keys("2090")
        driver.find_element_by_xpath("//*[@id= 'CURRENCY']/option[3]").click()
        driver.find_element_by_id("ZCDZ").send_keys("江门市新城区中山大道35号")
        driver.find_element_by_id("CYRYSL").send_keys("34")
        driver.find_element_by_id("BGDZ").send_keys("江门市新城区中山大道36号")
        driver.find_element_by_id("QYFZR").send_keys("李开建")
        driver.find_element_by_id("QYFZR_SJ").send_keys("16620953235")
        driver.find_element_by_id("LXDZ").send_keys("江门市新城区中山大道37号")
        driver.find_element_by_id("YZBM").send_keys("448000")
        driver.find_element_by_id("DZYX").send_keys("34874377@qq.com")
        driver.find_element_by_id("QYWZ").send_keys("http://125.91.215.239:8090/qyzxsq.aspx")
        driver.find_element_by_id("LXR").send_keys("李开复")
        driver.find_element_by_id("LXDH").send_keys("18845656788")
        driver.find_element_by_id("JBRXM").send_keys("李凯")
        driver.find_element_by_id("JBRSFZHM").send_keys("420804199005231122")
        driver.find_element_by_id("JBRYDDH").send_keys("16620953235")
        driver.find_element_by_id("GDDH").send_keys("87876566")
        driver.find_element_by_id("JYFW").send_keys("全部范围")
        driver.find_element_by_id("next").click()
        time.sleep(2)
        # # #新增资质信息切换 iframe
        #新增股东信息 切换iframe
        driver.implicitly_wait(3)
        driver.find_element_by_id("btnAddGDXX").click()
        # gdxx = driver.find_element_by_xpath("//*[@src = 'GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        gdxx = driver.find_element_by_xpath("//*[@src = 'Dialog/GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        driver.switch_to.frame(gdxx)
        driver.find_element_by_xpath("//*[@id= 'ZRRBZ']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("LXDH").send_keys("87895644")
        driver.find_element_by_id("XM").send_keys("李建军")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道38号")
        driver.find_element_by_id("FRXM").send_keys("李科技")
        driver.find_element_by_id("FRDH").send_keys("13878765655")
        driver.find_element_by_id("ZJHM").send_keys("422202199002203464")
        driver.find_element_by_id("TZJE").send_keys("3000")
        driver.find_element_by_id("TZBL").send_keys("46")
        driver.switch_to.default_content()
        time.sleep(3)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(4)
        driver.find_element_by_id("next").click()
        #新增从业人员1，切换iframe
        driver.implicitly_wait(3)

        #新增从业人员2
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("邹空间")
        driver.find_element_by_id("ZJHM").send_keys("350304198610111495")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("11"+a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDR11"+a)
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员3
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李快捷")
        driver.find_element_by_id("ZJHM").send_keys("429000197701012636")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("12"+a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[3]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDR12"+a)
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员4
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李青")
        driver.find_element_by_id("ZJHM").send_keys("46902619861215171X")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("13"+a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[4]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDR13"+a)
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员6
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("吴军")
        driver.find_element_by_id("ZJHM").send_keys("440106199203078411")
        driver.find_element_by_id("LXDH").send_keys("18865676567")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("14"+a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDR14"+a)
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        #新增从业人员7
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("刘明")
        driver.find_element_by_id("ZJHM").send_keys("440104199003078270")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("15"+a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[2]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDR15"+a)
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(5)
        driver.find_element_by_id("next").click()
         #填写诚信档案
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'ZCLSGX']/option[4]").click()
        driver.find_element_by_name("DJJG").send_keys("江门公安")
        driver.find_element_by_name("RZZW00").send_keys("农民")
        driver.find_element_by_name("RZZC00").send_keys("种地")
        #销售人信息
        driver.implicitly_wait(3)
        driver.find_element_by_name("XM01").send_keys("李科教")
        driver.find_element_by_name("SFZH01").send_keys("422202199002203464")
        driver.find_element_by_name("SJHM01").send_keys("16656543233")
        driver.find_element_by_name("RZZW01").send_keys("公务员")
        driver.find_element_by_name("RZZC01").send_keys("教师")
        driver.find_element_by_name("ZCZH01").send_keys("ADS434343")
        driver.find_element_by_name("ZCLB01").send_keys("一级")
        #财务信息
        driver.implicitly_wait(3)
        driver.find_element_by_name("XM02").send_keys("李可见")
        driver.find_element_by_name("SFZH02").send_keys("422202199002203464")
        driver.find_element_by_name("SJHM02").send_keys("13856543233")
        driver.find_element_by_name("RZZW02").send_keys("公务员")
        driver.find_element_by_name("RZZC02").send_keys("医生")
        driver.find_element_by_name("ZCZH02").send_keys("ASEW4343432")
        driver.find_element_by_name("ZCLB02").send_keys("二级")
        driver.find_element_by_id("next").click()
        time.sleep(2)
        APP_ID = "16230456"
        API_KEY = "8N2P8sUIB36F3imeui8tyflo"
        SECRET_KEY = "9p291bmDeprXN3k6bgIBrShTIHEkVSDB "
        client = AipOcr(APP_ID, API_KEY, SECRET_KEY)
        """ 读取图片 """
        def get_file_content(filePath):
            with open(filePath, 'rb') as fp:
                return fp.read()
        def getPic():
            #获取截图
            driver.get_screenshot_as_file('screenshot.png')
            #获取指定元素位置
            element = driver.find_element_by_xpath('//*[@id="yzm_tjsq"]')
            print(element.size)
            print(element.location)
            #获取位置不准，进行微调
            left = int(element.location['x'])
            top = int(element.location['y'])
            right = int(element.location['x'] + element.size['width'])
            bottom = int(element.location['y'] + element.size['height'])
            #通过Image处理图像
            im = Image.open('screenshot.png')
            im = im.crop((left, top, right, bottom))
            im.save('code.png')
        def getChar():
            getPic()
            image = get_file_content('code.png')
            """ 调用通用文字识别（高精度版） """
            result = client.basicAccurate(image)
            words_result = result.get("words_result")
            #删除屏幕截图
            os.remove('screenshot.png')
            #删除验证码截图
            os.remove('code.png')
            print(words_result)
            ss = words_result[0].get("words")
            #删除空格
            ss = ss.replace(' ','')
            return(ss)
        driver.find_element_by_xpath('//*[@id="code_"]').send_keys(getChar())
        # 填写材料提交
        time.sleep(7)
        driver.find_element_by_id("cxmm").send_keys("123123")
        time.sleep(3)
        driver.find_element_by_id("btnSave").click()
        time.sleep(10)
        a = driver.find_element_by_xpath("//*[@id = 'aui_content']").text
        print(a)
        while a == '验证码错误！':
            driver.find_element_by_xpath("//*[@class = 'aui_close']").click()  # 点关闭知道了
            time.sleep(2)
            driver.find_element_by_xpath('//*[@id="code_"]').clear() #清空验证码
            APP_ID = "16230456"
            API_KEY = "8N2P8sUIB36F3imeui8tyflo"
            SECRET_KEY = "9p291bmDeprXN3k6bgIBrShTIHEkVSDB "
            client = AipOcr(APP_ID, API_KEY, SECRET_KEY)
            """ 读取图片 """

            def get_file_content(filePath):
                with open(filePath, 'rb') as fp:
                    return fp.read()

            def getPic():
                # 获取截图
                driver.get_screenshot_as_file('screenshot.png')
                # 获取指定元素位置
                element = driver.find_element_by_xpath('//*[@id="yzm_tjsq"]')
                print(element.size)
                print(element.location)
                # 获取位置不准，进行微调
                left = int(element.location['x'])
                top = int(element.location['y'])
                right = int(element.location['x'] + element.size['width'])
                bottom = int(element.location['y'] + element.size['height'])
                # 通过Image处理图像
                im = Image.open('screenshot.png')
                im = im.crop((left, top, right, bottom))
                im.save('code.png')
            def getChar():
                getPic()
                image = get_file_content('code.png')
                """ 调用通用文字识别（高精度版） """
                result = client.basicAccurate(image)
                words_result = result.get("words_result")
                # 删除屏幕截图
                os.remove('screenshot.png')
                # 删除验证码截图
                os.remove('code.png')
                print(words_result)
                ss = words_result[0].get("words")
                # 删除空格
                ss = ss.replace(' ', '')
                return (ss)
            driver.find_element_by_xpath('//*[@id="code_"]').send_keys(getChar())  #输入验证码
            # 填写材料提交
            time.sleep(7)
            driver.find_element_by_id("btnSave").click()
            if a =='验证码错误！':  # 如果弹框出来了，就点确定
                driver.find_element_by_xpath("//*[@class = 'aui_close']").click()  # 点关闭知道了
            else:  # 否则就pass通过
                pass
        t = driver.find_element_by_xpath("//*[text()= '信息添加成功!']").text
         # print(t)
        self.assertTrue(t == '信息添加成功!')
        driver.close()
        ###
    def test_02(self):
        '''同名企业同机构下面只能存在一个，否则提示：企业名称"江门明分两有限公司"已存在并且非注销状态，不能再次申请!'''
        time.sleep(2)
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
        time.sleep(5)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(5)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(5)
        # 填写企业基本信息
        a = "E83968"
        b = "明金坷"  # 明分间明分间
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys("江门" + b + "有限公司")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys(b)
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("87876766")
        driver.find_element_by_xpath("//*[@id= 'FRXB']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'ZJLX']/option[4]").click()
        driver.find_element_by_id("FRSFZH").send_keys("3RER" + a)
        driver.find_element_by_id("YYZZH").send_keys("AA9887773")
        driver.find_element_by_id("ZZRQ").send_keys("2019-04-07")
        driver.find_element_by_id("YYZZDQR").send_keys("2024-04-07")
        driver.find_element_by_xpath("//*[@id= 'DJZCLX']/option[2]").click()
        driver.find_element_by_id("ZCZB").send_keys("2090")
        driver.find_element_by_xpath("//*[@id= 'CURRENCY']/option[3]").click()
        driver.find_element_by_id("ZCDZ").send_keys("江门市新城区中山大道35号")
        driver.find_element_by_id("CYRYSL").send_keys("34")
        driver.find_element_by_id("BGDZ").send_keys("江门市新城区中山大道36号")
        driver.find_element_by_id("QYFZR").send_keys("李开建")
        driver.find_element_by_id("QYFZR_SJ").send_keys("16620953235")
        driver.find_element_by_id("LXDZ").send_keys("江门市新城区中山大道37号")
        driver.find_element_by_id("YZBM").send_keys("448000")
        driver.find_element_by_id("DZYX").send_keys("34874377@qq.com")
        driver.find_element_by_id("QYWZ").send_keys("http://168.168.28.17:8080/qyzxsq.aspx")
        driver.find_element_by_id("LXR").send_keys("李开复")
        driver.find_element_by_id("LXDH").send_keys("18845656788")
        driver.find_element_by_id("JBRXM").send_keys("李凯")
        driver.find_element_by_id("JBRSFZHM").send_keys("420804199005231122")
        driver.find_element_by_id("JBRYDDH").send_keys("16620953235")
        driver.find_element_by_id("GDDH").send_keys("87876566")
        driver.find_element_by_id("JYFW").send_keys("全部范围")
        driver.find_element_by_id("next").click()
        time.sleep(2)
        # # #新增资质信息切换 iframe
        # 新增股东信息 切换iframe
        driver.implicitly_wait(3)
        driver.find_element_by_id("btnAddGDXX").click()
        time.sleep(5)
        gdxx = driver.find_element_by_xpath("//*[@src = 'Dialog/GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        # gdxx = driver.find_element_by_xpath("//*[@src = 'Dialog/GDXX.aspx?Jgid=91679226-6e6c-4b90-b60f-6f4b87291133']")
        driver.switch_to.frame(gdxx)
        time.sleep(5)
        driver.find_element_by_xpath("//*[@id= 'ZRRBZ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("LXDH").send_keys("87895644")
        driver.find_element_by_id("XM").send_keys("李建军")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道38号")
        # driver.find_element_by_id("FRXM").send_keys("李科技")
        # driver.find_element_by_id("FRDH").send_keys("13878765655")
        driver.find_element_by_xpath("//*[@id= 'ZJLX']/option[1]").click()
        driver.find_element_by_id("ZJHM").send_keys("422202199002203464")
        driver.find_element_by_id("TZJE").send_keys("3000")
        driver.find_element_by_id("TZBL").send_keys("46")
        driver.switch_to.default_content()
        time.sleep(3)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(4)
        driver.find_element_by_id("next").click()
        # 新增从业人员1，切换iframe
        driver.implicitly_wait(3)
        # 新增从业人员2
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        time.sleep(5)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("邹空间")
        driver.find_element_by_id("ZJHM").send_keys("350304198610111495")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("43" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员3
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        time.sleep(5)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李快捷")
        driver.find_element_by_id("ZJHM").send_keys("429000197701012636")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("A" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[3]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员4
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        time.sleep(5)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李青")
        driver.find_element_by_id("ZJHM").send_keys("46902619861215171X")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("AR3" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[4]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员5
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        time.sleep(5)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("刘雪花")
        driver.find_element_by_id("ZJHM").send_keys("441622198110077165")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("A43" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[2]").click()
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[5]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("本科")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员6
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        time.sleep(5)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("吴军")
        driver.find_element_by_id("ZJHM").send_keys("440106199203078411")
        driver.find_element_by_id("LXDH").send_keys("18865676567")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("AR3" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员7
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        time.sleep(5)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("刘明")
        driver.find_element_by_id("ZJHM").send_keys("440104199003078270")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("473" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[2]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(5)
        driver.find_element_by_id("next").click()
        # 填写诚信档案
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'ZCLSGX']/option[4]").click()
        driver.find_element_by_name("DJJG").send_keys("江门公安")
        driver.find_element_by_name("RZZW00").send_keys("农民")
        driver.find_element_by_name("RZZC00").send_keys("种地")
        #销售人信息
        driver.implicitly_wait(3)
        driver.find_element_by_name("XM01").send_keys("李科教")
        driver.find_element_by_name("SFZH01").send_keys("422202199002203464")
        driver.find_element_by_name("SJHM01").send_keys("16656543233")
        driver.find_element_by_name("RZZW01").send_keys("公务员")
        driver.find_element_by_name("RZZC01").send_keys("教师")
        driver.find_element_by_name("ZCZH01").send_keys("ADS434343")
        driver.find_element_by_name("ZCLB01").send_keys("一级")
        #财务信息
        driver.implicitly_wait(3)
        driver.find_element_by_name("XM02").send_keys("李可见")
        driver.find_element_by_name("SFZH02").send_keys("422202199002203464")
        driver.find_element_by_name("SJHM02").send_keys("13856543233")
        driver.find_element_by_name("RZZW02").send_keys("公务员")
        driver.find_element_by_name("RZZC02").send_keys("医生")
        driver.find_element_by_name("ZCZH02").send_keys("ASEW4343432")
        driver.find_element_by_name("ZCLB02").send_keys("二级")
        driver.find_element_by_id("next").click()
        # #####################################################
        APP_ID = "16230456"
        API_KEY = "8N2P8sUIB36F3imeui8tyflo"
        SECRET_KEY = "9p291bmDeprXN3k6bgIBrShTIHEkVSDB "
        client = AipOcr(APP_ID, API_KEY, SECRET_KEY)
        """ 读取图片 """

        def get_file_content(filePath):
            with open(filePath, 'rb') as fp:
                return fp.read()

        def getPic():
            # 获取截图
            driver.get_screenshot_as_file('screenshot.png')
            # 获取指定元素位置
            element = driver.find_element_by_xpath('//*[@id="yzm_tjsq"]')
            print(element.size)
            print(element.location)
            # 获取位置不准，进行微调
            left = int(element.location['x'])
            top = int(element.location['y'])
            right = int(element.location['x'] + element.size['width'])
            bottom = int(element.location['y'] + element.size['height'])

            # 通过Image处理图像
            im = Image.open('screenshot.png')
            im = im.crop((left, top, right, bottom))
            im.save('code.png')

        def getChar():
            getPic()
            image = get_file_content('code.png')
            """ 调用通用文字识别（高精度版） """
            result = client.basicAccurate(image)
            words_result = result.get("words_result")
            # 删除屏幕截图
            os.remove('screenshot.png')
            # 删除验证码截图
            os.remove('code.png')
            print(words_result)
            ss = words_result[0].get("words")
            # 删除空格
            ss = ss.replace(' ', '')
            return (ss)

        driver.find_element_by_xpath('//*[@id="code_"]').send_keys(getChar())
        # 填写材料提交
        time.sleep(15)
        driver.find_element_by_id("cxmm").send_keys("123123")
        time.sleep(3)
        driver.find_element_by_id("btnSave").click()
        time.sleep(10)
        t = driver.find_element_by_xpath("//*[@class = 'aui_main']").text
        print(t)
        time.sleep(3)
        self.assertTrue(t == '企业名称"江门明金坷有限公司"已存在并且非注销状态，不能再次申请!')
        driver.close()
    def test_03(self):
        '''同名企业同机构下面,企业类别经纪机构已存在，开发商类别入网申请成功'''
        time.sleep(2)
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
        time.sleep(5)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(5)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(5)
        # 填写企业基本信息
        a = "E8301"
        # b = "明明天"
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys("江西金山房地产经纪机构")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys("金山")
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("87876766")
        driver.find_element_by_xpath("//*[@id= 'FRXB']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'ZJLX']/option[4]").click()
        driver.find_element_by_id("FRSFZH").send_keys("3RER" + a)
        driver.find_element_by_id("YYZZH").send_keys("AA9887773")
        driver.find_element_by_id("ZZRQ").send_keys("2019-04-07")
        driver.find_element_by_id("YYZZDQR").send_keys("2024-04-07")
        driver.find_element_by_xpath("//*[@id= 'DJZCLX']/option[2]").click()
        driver.find_element_by_id("ZCZB").send_keys("2090")
        driver.find_element_by_xpath("//*[@id= 'CURRENCY']/option[3]").click()
        driver.find_element_by_id("ZCDZ").send_keys("江门市新城区中山大道35号")
        driver.find_element_by_id("CYRYSL").send_keys("34")
        driver.find_element_by_id("BGDZ").send_keys("江门市新城区中山大道36号")
        driver.find_element_by_id("QYFZR").send_keys("李开建")
        driver.find_element_by_id("QYFZR_SJ").send_keys("16620953235")
        driver.find_element_by_id("LXDZ").send_keys("江门市新城区中山大道37号")
        driver.find_element_by_id("YZBM").send_keys("448000")
        driver.find_element_by_id("DZYX").send_keys("34874377@qq.com")
        driver.find_element_by_id("QYWZ").send_keys("http://125.91.215.239:8090/qyzxsq.aspx")
        driver.find_element_by_id("LXR").send_keys("李开复")
        driver.find_element_by_id("LXDH").send_keys("18845656788")
        driver.find_element_by_id("JBRXM").send_keys("李凯")
        driver.find_element_by_id("JBRSFZHM").send_keys("420804199005231122")
        driver.find_element_by_id("JBRYDDH").send_keys("16620953235")
        driver.find_element_by_id("GDDH").send_keys("87876566")
        driver.find_element_by_id("JYFW").send_keys("全部范围")
        driver.find_element_by_id("next").click()
        time.sleep(2)
        # # #新增资质信息切换 iframe
        # 新增股东信息 切换iframe
        driver.implicitly_wait(3)
        driver.find_element_by_id("btnAddGDXX").click()
        # gdxx = driver.find_element_by_xpath("//*[@src = 'GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        gdxx = driver.find_element_by_xpath("//*[@src = 'Dialog/GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        driver.switch_to.frame(gdxx)
        driver.find_element_by_xpath("//*[@id= 'ZRRBZ']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("LXDH").send_keys("87895644")
        driver.find_element_by_id("XM").send_keys("李建军")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道38号")
        driver.find_element_by_id("FRXM").send_keys("李科技")
        driver.find_element_by_id("FRDH").send_keys("13878765655")
        driver.find_element_by_id("ZJHM").send_keys("422202199002203464")
        driver.find_element_by_id("TZJE").send_keys("3000")
        driver.find_element_by_id("TZBL").send_keys("46")
        driver.switch_to.default_content()
        time.sleep(3)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(4)
        driver.find_element_by_id("next").click()
        # 新增从业人员1，切换iframe
        driver.implicitly_wait(3)
       # 新增从业人员2
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("邹空间")
        driver.find_element_by_id("ZJHM").send_keys("350304198610111495")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("21" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员3
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李快捷")
        driver.find_element_by_id("ZJHM").send_keys("429000197701012636")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("22" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[3]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员4
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李青")
        driver.find_element_by_id("ZJHM").send_keys("46902619861215171X")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("23" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[4]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员5
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("刘雪花")
        driver.find_element_by_id("ZJHM").send_keys("441622198110077165")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("24" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[2]").click()
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[5]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("本科")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员6
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("吴军")
        driver.find_element_by_id("ZJHM").send_keys("440106199203078411")
        driver.find_element_by_id("LXDH").send_keys("18865676567")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("25" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员7
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("刘明")
        driver.find_element_by_id("ZJHM").send_keys("440104199003078270")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("26" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[2]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(5)
        driver.find_element_by_id("next").click()
         #填写诚信档案
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'ZCLSGX']/option[4]").click()
        driver.find_element_by_name("DJJG").send_keys("江门公安")
        driver.find_element_by_name("RZZW00").send_keys("农民")
        driver.find_element_by_name("RZZC00").send_keys("种地")
        #销售人信息
        driver.implicitly_wait(3)
        driver.find_element_by_name("XM01").send_keys("李科教")
        driver.find_element_by_name("SFZH01").send_keys("422202199002203464")
        driver.find_element_by_name("SJHM01").send_keys("16656543233")
        driver.find_element_by_name("RZZW01").send_keys("公务员")
        driver.find_element_by_name("RZZC01").send_keys("教师")
        driver.find_element_by_name("ZCZH01").send_keys("ADS434343")
        driver.find_element_by_name("ZCLB01").send_keys("一级")
        #财务信息
        driver.implicitly_wait(3)
        driver.find_element_by_name("XM02").send_keys("李可见")
        driver.find_element_by_name("SFZH02").send_keys("422202199002203464")
        driver.find_element_by_name("SJHM02").send_keys("13856543233")
        driver.find_element_by_name("RZZW02").send_keys("公务员")
        driver.find_element_by_name("RZZC02").send_keys("医生")
        driver.find_element_by_name("ZCZH02").send_keys("ASEW4343432")
        driver.find_element_by_name("ZCLB02").send_keys("二级")
        driver.find_element_by_id("next").click()
        APP_ID = "16230456"
        API_KEY = "8N2P8sUIB36F3imeui8tyflo"
        SECRET_KEY = "9p291bmDeprXN3k6bgIBrShTIHEkVSDB "
        client = AipOcr(APP_ID, API_KEY, SECRET_KEY)
        """ 读取图片 """

        def get_file_content(filePath):
            with open(filePath, 'rb') as fp:
                return fp.read()

        def getPic():
            # 获取截图
            driver.get_screenshot_as_file('screenshot.png')
            # 获取指定元素位置
            element = driver.find_element_by_xpath('//*[@id="yzm_tjsq"]')
            print(element.size)
            print(element.location)
            # 获取位置不准，进行微调
            left = int(element.location['x'])
            top = int(element.location['y'])
            right = int(element.location['x'] + element.size['width'])
            bottom = int(element.location['y'] + element.size['height'])

            # 通过Image处理图像
            im = Image.open('screenshot.png')
            im = im.crop((left, top, right, bottom))
            im.save('code.png')

        def getChar():
            getPic()
            image = get_file_content('code.png')
            """ 调用通用文字识别（高精度版） """
            result = client.basicAccurate(image)
            words_result = result.get("words_result")
            # 删除屏幕截图
            os.remove('screenshot.png')
            # 删除验证码截图
            os.remove('code.png')
            print(words_result)
            ss = words_result[0].get("words")
            # 删除空格
            ss = ss.replace(' ', '')
            return (ss)

        driver.find_element_by_xpath('//*[@id="code_"]').send_keys(getChar())
        # 填写材料提交
        driver.find_element_by_id("cxmm").send_keys("123123")
        time.sleep(8)
        driver.find_element_by_id("btnSave").click()
        time.sleep(10)
        t = driver.find_element_by_xpath("//*[text()= '信息添加成功!']").text
        # print(t)
        self.assertTrue(t == '信息添加成功!')
        driver.close()
    def test_04(self):
        '''江门开发商企基本信息电话号码不能小于8位'''
        time.sleep(2)
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
        time.sleep(8)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(8)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(8)
        # 填写企业基本信息
        a = "E8388"
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys("中国")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys("中国")
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("875455")
        driver.find_element_by_xpath("//*[@id= 'FRXB']/option[2]").click()
        time.sleep(3)
        t = driver.find_element_by_xpath("//*[@id = 'FRDBDH-error']").text
        self.assertTrue(t == '请正确填写您的联系方式')
        time.sleep(5)
        driver.close()
    def test_05(self):
        '''江门开发商企业简称不能为数字，特殊字符'''
        time.sleep(2)
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
        time.sleep(5)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(5)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(5)
        # 填写企业基本信息
        a = "E8388"
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys("65")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys("65")
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("87876766")
        time.sleep(2)
        t = driver.find_element_by_xpath("//*[@id = 'QWJC-error']").text
        # print(t)
        self.assertTrue(t == '只能包含中文字符。')
        driver.close()
    def test_06(self):
        '''江门开发商企基本信息电话号码不能超过11位'''
        time.sleep(2)
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
        time.sleep(8)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(8)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(8)
        # 填写企业基本信息
        a = "E8388"
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys("中国")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys("中国")
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("87455454545454545")
        driver.find_element_by_xpath("//*[@id= 'FRXB']/option[2]").click()
        time.sleep(3)
        t = driver.find_element_by_xpath("//*[@id = 'FRDBDH-error']").text
        self.assertTrue(t == '请正确填写您的联系方式')
        time.sleep(5)
        driver.close()
    def test_07(self):
        '''江门开发商企业入网要满足从业人员大于5人，否则提示：专业管理人员人数不足5人！'''
        time.sleep(2)
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
        time.sleep(8)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(8)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(5)
        # 填写企业基本信息
        a = "E8390"
        b = "明分"
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys("江门" + b + "有限公司")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys(b)
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("87876766")
        driver.find_element_by_xpath("//*[@id= 'FRXB']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'ZJLX']/option[4]").click()
        driver.find_element_by_id("FRSFZH").send_keys("3RER" + a)
        driver.find_element_by_id("YYZZH").send_keys("AA9887773")
        driver.find_element_by_id("ZZRQ").send_keys("2019-04-07")
        driver.find_element_by_id("YYZZDQR").send_keys("2024-04-07")
        driver.find_element_by_xpath("//*[@id= 'DJZCLX']/option[2]").click()
        driver.find_element_by_id("ZCZB").send_keys("2090")
        driver.find_element_by_xpath("//*[@id= 'CURRENCY']/option[3]").click()
        driver.find_element_by_id("ZCDZ").send_keys("江门市新城区中山大道35号")
        driver.find_element_by_id("CYRYSL").send_keys("34")
        driver.find_element_by_id("BGDZ").send_keys("江门市新城区中山大道36号")
        driver.find_element_by_id("QYFZR").send_keys("李开建")
        driver.find_element_by_id("QYFZR_SJ").send_keys("16620953235")
        driver.find_element_by_id("LXDZ").send_keys("江门市新城区中山大道37号")
        driver.find_element_by_id("YZBM").send_keys("448000")
        driver.find_element_by_id("DZYX").send_keys("34874377@qq.com")
        driver.find_element_by_id("QYWZ").send_keys("http://125.91.215.239:8090/qyzxsq.aspx")
        driver.find_element_by_id("LXR").send_keys("李开复")
        driver.find_element_by_id("LXDH").send_keys("18845656788")
        driver.find_element_by_id("JBRXM").send_keys("李凯")
        driver.find_element_by_id("JBRSFZHM").send_keys("420804199005231122")
        driver.find_element_by_id("JBRYDDH").send_keys("16620953235")
        driver.find_element_by_id("GDDH").send_keys("87876566")
        driver.find_element_by_id("JYFW").send_keys("全部范围")
        driver.find_element_by_id("next").click()
        time.sleep(2)
        # # #新增资质信息切换 iframe
        # 新增股东信息 切换iframe
        driver.implicitly_wait(3)
        driver.find_element_by_id("btnAddGDXX").click()
        # gdxx = driver.find_element_by_xpath("//*[@src = 'GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        gdxx = driver.find_element_by_xpath("//*[@src = 'Dialog/GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        driver.switch_to.frame(gdxx)
        driver.find_element_by_xpath("//*[@id= 'ZRRBZ']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("LXDH").send_keys("87895644")
        driver.find_element_by_id("XM").send_keys("李建军")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道38号")
        driver.find_element_by_id("FRXM").send_keys("李科技")
        driver.find_element_by_id("FRDH").send_keys("13878765655")
        driver.find_element_by_id("ZJHM").send_keys("422202199002203464")
        driver.find_element_by_id("TZJE").send_keys("3000")
        driver.find_element_by_id("TZBL").send_keys("46")
        driver.switch_to.default_content()
        time.sleep(3)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(4)
        driver.find_element_by_id("next").click()
        # 新增从业人员1，切换iframe
        driver.implicitly_wait(3)
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李开奖")
        driver.find_element_by_id("ZJHM").send_keys("422202199002203464")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("ARER43" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[6]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        # driver.find_element_by_id("WHCD").send_keys("高中")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员2
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("邹空间")
        driver.find_element_by_id("ZJHM").send_keys("350304198610111495")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("43" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员3
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李快捷")
        driver.find_element_by_id("ZJHM").send_keys("429000197701012636")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("A" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[3]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员4
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李青")
        driver.find_element_by_id("ZJHM").send_keys("46902619861215171X")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("AR3" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[4]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        driver.find_element_by_id("next").click()
        time.sleep(3)
        t = driver.find_element_by_xpath("//*[@class = 'aui_content']").text
        # print(t)
        self.assertTrue(t == '专业管理人员人数不足5人！')
        time.sleep(5)
        driver.close()
    def test_08(self):
        '''江门开发商入网从业人员职称，业务负责人需具有相应专业中级以上职称！才可以提交申请'''
        time.sleep(2)
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
        driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
        time.sleep(8)
        driver.find_element_by_id("chkFDCKFJG").click()
        time.sleep(8)
        # Select(driver.find_element_by_id("QXH")).select_by_value("441602")
        driver.find_element_by_xpath("//*[@id = 'QXH']/option[1]").click()
        time.sleep(5)
        # 填写企业基本信息
        a = "E8390"
        b = "明分"
        driver.implicitly_wait(5)
        driver.find_element_by_xpath("//*[@id='next']").click()
        time.sleep(6)
        driver.find_element_by_id("QYMC").send_keys("江门" + b + "有限公司")
        time.sleep(1)
        driver.find_element_by_id("QWJC").send_keys(b)
        driver.find_element_by_id("FRDB").send_keys("李框架")
        driver.find_element_by_id("FRDBDH").send_keys("87876766")
        driver.find_element_by_xpath("//*[@id= 'FRXB']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'ZJLX']/option[4]").click()
        driver.find_element_by_id("FRSFZH").send_keys("3RER" + a)
        driver.find_element_by_id("YYZZH").send_keys("AA9887773")
        driver.find_element_by_id("ZZRQ").send_keys("2019-04-07")
        driver.find_element_by_id("YYZZDQR").send_keys("2024-04-07")
        driver.find_element_by_xpath("//*[@id= 'DJZCLX']/option[2]").click()
        driver.find_element_by_id("ZCZB").send_keys("2090")
        driver.find_element_by_xpath("//*[@id= 'CURRENCY']/option[3]").click()
        driver.find_element_by_id("ZCDZ").send_keys("江门市新城区中山大道35号")
        driver.find_element_by_id("CYRYSL").send_keys("34")
        driver.find_element_by_id("BGDZ").send_keys("江门市新城区中山大道36号")
        driver.find_element_by_id("QYFZR").send_keys("李开建")
        driver.find_element_by_id("QYFZR_SJ").send_keys("16620953235")
        driver.find_element_by_id("LXDZ").send_keys("江门市新城区中山大道37号")
        driver.find_element_by_id("YZBM").send_keys("448000")
        driver.find_element_by_id("DZYX").send_keys("34874377@qq.com")
        driver.find_element_by_id("QYWZ").send_keys("http://125.91.215.239:8090/qyzxsq.aspx")
        driver.find_element_by_id("LXR").send_keys("李开复")
        driver.find_element_by_id("LXDH").send_keys("18845656788")
        driver.find_element_by_id("JBRXM").send_keys("李凯")
        driver.find_element_by_id("JBRSFZHM").send_keys("420804199005231122")
        driver.find_element_by_id("JBRYDDH").send_keys("16620953235")
        driver.find_element_by_id("GDDH").send_keys("87876566")
        driver.find_element_by_id("JYFW").send_keys("全部范围")
        driver.find_element_by_id("next").click()
        time.sleep(2)
        # # #新增资质信息切换 iframe
        # 新增股东信息 切换iframe
        driver.implicitly_wait(3)
        driver.find_element_by_id("btnAddGDXX").click()
        # gdxx = driver.find_element_by_xpath("//*[@src = 'GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        gdxx = driver.find_element_by_xpath("//*[@src = 'Dialog/GDXX.aspx?Jgid=FC830662-EA75-427C-9A82-443B91E383CB']")
        driver.switch_to.frame(gdxx)
        driver.find_element_by_xpath("//*[@id= 'ZRRBZ']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("LXDH").send_keys("87895644")
        driver.find_element_by_id("XM").send_keys("李建军")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道38号")
        driver.find_element_by_id("FRXM").send_keys("李科技")
        driver.find_element_by_id("FRDH").send_keys("13878765655")
        driver.find_element_by_id("ZJHM").send_keys("422202199002203464")
        driver.find_element_by_id("TZJE").send_keys("3000")
        driver.find_element_by_id("TZBL").send_keys("46")
        driver.switch_to.default_content()
        time.sleep(3)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(4)
        driver.find_element_by_id("next").click()
        # 新增从业人员1，切换iframe
        driver.implicitly_wait(3)
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李开奖")
        driver.find_element_by_id("ZJHM").send_keys("422202199002203464")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("ARER43" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[6]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        # driver.find_element_by_id("WHCD").send_keys("高中")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员2
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("邹空间")
        driver.find_element_by_id("ZJHM").send_keys("350304198610111495")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("43" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[5]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[1]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员3
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        # driver.switch_to_frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李快捷")
        driver.find_element_by_id("ZJHM").send_keys("429000197701012636")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("A" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[4]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[3]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        # 新增从业人员4
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("李青")
        driver.find_element_by_id("ZJHM").send_keys("46902619861215171X")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("AR3" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[3]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[4]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("总经理")
        driver.find_element_by_id("XL").send_keys("大专")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        driver.find_element_by_id("btnAddQYRY").click()
        cyry = driver.find_element_by_xpath("//*[@src = 'Dialog/JMCYRY.aspx']")
        driver.switch_to.frame(cyry)
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'XB']/option[2]").click()
        driver.find_element_by_id("XM").send_keys("刘雪花")
        driver.find_element_by_id("ZJHM").send_keys("441622198110077165")
        driver.find_element_by_id("LXDH").send_keys("18865676767")
        driver.find_element_by_id("ZGLX").send_keys("一级")
        driver.find_element_by_id("ZYZSBH").send_keys("A43" + a)
        driver.find_element_by_xpath("//*[@id= 'ZCDJ']/option[4]").click()
        driver.implicitly_wait(3)
        driver.find_element_by_xpath("//*[@id= 'ZY']/option[2]").click()
        driver.find_element_by_xpath("//*[@id= 'YWFZRLB']/option[5]").click()
        driver.find_element_by_class_name("dhxcombo_input").send_keys("法定代表人")
        driver.find_element_by_id("XL").send_keys("本科")
        driver.find_element_by_id("DZ").send_keys("江门市新城区中山大道39号")
        driver.find_element_by_id("SBH").send_keys("FDRE543DSDS32")
        driver.find_element_by_id("FZSJ").send_keys("2019-04-07")
        driver.find_element_by_id("CSRQ").send_keys("2000-04-07")
        driver.find_element_by_id("RZZW").send_keys("公务员")
        driver.find_element_by_id("RZZC").send_keys("工程师")
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@class= 'ui-dialog-autofocus']").click()
        time.sleep(2)
        driver.find_element_by_id("next").click()
        time.sleep(3)
        t = driver.find_element_by_xpath(" //*[@class = 'aui_content']").text
        time.sleep(2)
        self.assertTrue(t == '业务负责人需具有相应专业中级以上职称！')
        time.sleep(2)
        driver.close()

# \        self.assertTrue(t == '业务负责人需具有相应专业中级以上职称！')

    # def test_09(self):
    #     '''企业入网申请提交职能端退件，可以通过申请号密码，查询修改信息再次提交'''
    #     driver = webdriver.Firefox()
    #     driver.maximize_window()
    #     driver.implicitly_wait(2)  # 设置全局隐性等待时间，单位秒
    #     driver.get('http://168.168.28.17:8080/qyzxsq.aspx')  # http://125.91.215.239:8090/
    #     time.sleep(8)
    #     driver.find_element_by_xpath("//*[@id='query_wssqh']").send_keys("44160209201906280019") #输入网上申请号
    #     driver.find_element_by_xpath("//*[@id='query_pwd']").send_keys("123123")#输入密码
    #     driver.find_element_by_xpath("//*[@id='queryBtn']").click()#点查询
    #     time.sleep(12)
    #     driver.find_element_by_xpath("//*[text()= '知道了']").click()#点知道了
    #     time.sleep(3)
    #     driver.find_element_by_xpath("//*[text()= '企业基本信息']").click()#点企业基本信息
    #     # driver.find_element_by_id("QYMC").clear()
    #     # driver.find_element_by_id("QWJC").clear()
    #     driver.find_element_by_id("FRDB").clear()
    #     driver.find_element_by_id("FRDBDH").clear()
    #     time.sleep(2)
    #     driver.find_element_by_xpath("//*[@id= 'DJZCLX']/option[4]").click()
    #     # driver.find_element_by_id("QYMC").send_keys("江门贴膜有限公司")
    #     # driver.find_element_by_id("QWJC").send_keys("贴膜")
    #     driver.find_element_by_id("FRDB").send_keys("李架新")
    #     driver.find_element_by_id("FRDBDH").send_keys("18872446625")
    #     driver.find_element_by_xpath("//*[@id= 'FRXB']/option[1]").click()
    #     driver.find_element_by_xpath("//*[@id= 'ZJLX']/option[3]").click()
    #     time.sleep(3)
    #     driver.find_element_by_xpath("//*[text()= '申请资料']").click()#点申请资料
    #     APP_ID = "16230456"
    #     API_KEY = "8N2P8sUIB36F3imeui8tyflo"
    #     SECRET_KEY = "9p291bmDeprXN3k6bgIBrShTIHEkVSDB "
    #     client = AipOcr(APP_ID, API_KEY, SECRET_KEY)
    #     """ 读取图片 """
    #
    #     def get_file_content(filePath):
    #         with open(filePath, 'rb') as fp:
    #             return fp.read()
    #
    #     def getPic():
    #         # 获取截图
    #         driver.get_screenshot_as_file('screenshot.png')
    #         # 获取指定元素位置
    #         element = driver.find_element_by_xpath('//*[@id="yzm_tjsq"]')
    #         print(element.size)
    #         print(element.location)
    #         # 获取位置不准，进行微调
    #         left = int(element.location['x'])
    #         top = int(element.location['y'])
    #         right = int(element.location['x'] + element.size['width'])
    #         bottom = int(element.location['y'] + element.size['height'])
    #
    #         # 通过Image处理图像
    #         im = Image.open('screenshot.png')
    #         im = im.crop((left, top, right, bottom))
    #         im.save('code.png')
    #
    #     def getChar():
    #         getPic()
    #         image = get_file_content('code.png')
    #         """ 调用通用文字识别（高精度版） """
    #         result = client.basicAccurate(image)
    #         words_result = result.get("words_result")
    #         # 删除屏幕截图
    #         os.remove('screenshot.png')
    #         # 删除验证码截图
    #         os.remove('code.png')
    #         print(words_result)
    #         ss = words_result[0].get("words")
    #         # 删除空格
    #         ss = ss.replace(' ', '')
    #         return (ss)
    #
    #     driver.find_element_by_xpath('//*[@id="code_"]').send_keys(getChar())
    #     #填写材料提交
    #     time.sleep(15)
    #     driver.find_element_by_id("cxmm").send_keys("123123")
    #     time.sleep(3)
    #     driver.find_element_by_id("btnSave").click()
    #     time.sleep(10)
    #     driver.switch_to_default_content()
    #     driver.find_element_by_xpath("//*[text()= '确定']").click()  # 点确定
    #     time.sleep(8)
    #     t = driver.find_element_by_xpath("//*[text()= '信息添加成功!']").text
    #     # print(t)
    #     self.assertTrue(t == '信息添加成功!')
    #     driver.close()
    #
    #
    #
    #     # driver.find_element_by_id("chkFDCKFJG").click()
    #
    #
    #
